import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { getServerSession } from 'next-auth'
import SessionProvider from '@/components/SessionProvider'
import NavMenu from '@/components/NavMenu'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <main className="mx-auto max-w-5xl text-sm flex gap-8 min-h-screen">
            <div className="min-h-screen max-h-screen overflow-y-auto bg-stone-800 text-white p-8 min-w-[200px]">
              <NavMenu />
            </div>
            <div className="p-8">
              {children}
            </div>
          </main>
        </SessionProvider>
      </body>
    </html>
  )
}
